# Generated by Django 2.2 on 2019-12-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Фотграфия', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
